language: dart
dart: dev

jobs:
  include:
  - stage: analyze
    script: dartanalyzer --fatal-warnings .
  - stage: analyze
    script: dartfmt --dry-run --set-exit-if-changed .
  - stage: build
    script: pub run build_runner build
  - stage: test
    script: pub run test --platform vm
  - stage: test
    script: pub run test --platform chrome
stages:
- analyze
- build
- test

sudo: required
cache:
  directories:
  - $HOME/.pub-cache
  - .dart_tool/build
