language: dart
dart: dev

jobs:
  include:
  - stage: analyze
    script: dartanalyzer --fatal-warnings .
  - stage: analyze
    script: dartfmt --dry-run --set-exit-if-changed .
  - stage: unit_test
    script: pub run test --platform vm
  - stage: unit_test
    script: pub run test --platform chrome
stages:
- analyze
- unit_test

sudo: required
cache:
  directories:
  - $HOME/.pub-cache
  - .dart_tool/build
