name: data
version: 0.0.2

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and algorithms to deal with data in Dart.

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'
dependencies:
  more: ^1.10.0
  collection: ^1.14.0
dev_dependencies:
  build_runner: ^0.9.0
  build_test: ^0.10.0
  build_web_compilers: ^0.4.0
  test: ^1.3.0
