name: data
version: 0.2.0

author: Lukas Renggli <renggli@gmail.com>
homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: '>=2.6.0 <3.0.0'
dependencies:
  collection: ^1.14.0
  meta: ^1.1.0
  more: ^1.18.0
dev_dependencies:
  test: ^1.6.0
