name: data
version: 0.11.0

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

publish_to: none
environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  collection: ^1.17.0
  meta: ^1.8.0
  more:
    path: ../MoreDart
    # git: https://github.com/renggli/dart-more.git
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
