name: data
version: 0.6.0-nullsafety.1

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  collection: ^1.15.0-nullsafety
  meta: ^1.3.0-nullsafety
  more: ^3.0.0-nullsafety
dev_dependencies:
  test: ^1.16.0-nullsafety
