name: data
version: 0.11.0

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: '>=2.16.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  more: ^3.5.0
dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.0
